# Generated by Django 2.2.3 on 2019-07-30 15:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('api_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateField()),
                ('location_detail', models.TextField()),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.CrimeType')),
            ],
        ),
    ]
