# Generated by Django 2.2.3 on 2019-07-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_Location_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_location_detail', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='crime',
            name='location_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Crime_Location_Detail'),
        ),
    ]
